-- Enable UUID extension if needed, though we use BigInt for Telegram IDs
-- create extension if not exists "uuid-ossp";

-- Table: users
CREATE TABLE IF NOT EXISTS users (
    tg_id BIGINT PRIMARY KEY,
    role TEXT CHECK (role IN ('parent', 'child')) NOT NULL,
    balance INTEGER DEFAULT 0,
    parent_id BIGINT REFERENCES users(tg_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: channels_whitelist
CREATE TABLE IF NOT EXISTS channels_whitelist (
    channel_id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT CHECK (status IN ('approved', 'banned')) DEFAULT 'approved',
    added_by BIGINT REFERENCES users(tg_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: tasks
-- Using SERIAL/IDENTITY for internal ID, since video_id might not be unique if tasks are repeated or have different params
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id TEXT NOT NULL,
    title TEXT NOT NULL,
    reward_amount INTEGER NOT NULL DEFAULT 50,
    status TEXT CHECK (status IN ('pending', 'completed', 'active')) DEFAULT 'active', -- 'active' meant for global availability
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: submissions
CREATE TABLE IF NOT EXISTS submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT REFERENCES tasks(id),
    user_id BIGINT REFERENCES users(tg_id),
    ai_score INTEGER CHECK (ai_score >= 0 AND ai_score <= 100),
    audio_text TEXT,
    verification_status TEXT CHECK (verification_status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Optional: RLS (Row Level Security) Policies
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- ... (Can add policies later as needed)
